-- 1. Users table
CREATE TABLE users (
    uid VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- 2. Game Rules table (Master Data)
CREATE TABLE game_rule (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- 3. Play Logs table (Aggregate Root)
CREATE TABLE play_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    generated_number INT NOT NULL,
    score INT NOT NULL,
    uid VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_play_log_user FOREIGN KEY (uid) REFERENCES users (uid)
);

-- 4. Log Rules table (Intermediate Table)
CREATE TABLE log_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    play_log_id BIGINT NOT NULL,
    game_rule_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_log_rule_play_log FOREIGN KEY (play_log_id) REFERENCES play_log (id),
    CONSTRAINT fk_log_rule_game_rule FOREIGN KEY (game_rule_id) REFERENCES game_rule (id)
);

CREATE INDEX idx_play_log_score ON play_log (score DESC);
CREATE INDEX idx_play_log_uid ON play_log (uid);